#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2
#define TAPPING_TERM 180

#define MK_KINETIC_SPEED
#define MOUSEKEY_OVERLAP_RESET

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_INITIAL_SPEED 10
#define MOUSEKEY_MOVE_DELTA 200

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 10
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_INTERVAL 25
